# Generated by Django 5.0.6 on 2024-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('meeting_days', models.DateField()),
                ('academic_year', models.DateField()),
                ('class_status', models.CharField(max_length=30)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('general_performance', models.CharField(max_length=15)),
            ],
        ),
    ]
