# Generated by Django 5.0.6 on 2024-07-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classperiod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassPeriod',
        ),
    ]
