# Generated by Django 5.0.6 on 2024-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPeriod', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='teacher_first_name',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
    ]
